---
- set_fact:
    certbot: "{{ microk8s | combine(microk8s_overwrite, recursive=True) }}"
  when: microk8s_overwrite is defined

- name: sudo snap install microk8s --classic
  snap:
    name:
      - microk8s
      - kubectl
    classic: yes
  become: yes

- name: download helm from {{microk8s['helm']['src']}}
  ansible.builtin.unarchive:
    src: "{{microk8s['helm']['src']}}"
    dest: /tmp/helm3.tar.gz
    remote_src: yes
    checksum: "{{microk8s['helm']['checksum']}}"

- name: install helm3
  ansible.builtin.unarchive:
    src: /tmp/helm3.tar.gz
    dest: /usr/local/bin/helm3
    mode: 0755

- name: remove helm from /tmp
  ansible.builtin.file:
    path: /tmp/helm3.tar.gz
    state: absent

- name: wait for microk8s
  shell: microk8s status --wait-ready
  become: yes

- name: enable microk8s modules
  shell: microk8s enable {{microk8s['enable']}}
  become: yes
  when: microk8s['enable'] is defined

- name: install bash autocomplete
  apt:
    name: bash-completion
    state: present
  become: yes
