---
- name: sudo snap install microk8s --classic
  snap:
    name: microk8s
    classic: yes
  become: yes

- name: wait for microk8s
  shell: microk8s status --wait-ready
  become: yes

- name: enable microk8s modules
  shell: microk8s enable {{microk8s['enable']}}
  become: yes
