---
- set_fact:
    certbot: "{{ microk8s | combine(microk8s_overwrite, recursive=True) }}"
  when: microk8s_overwrite is defined

- name: enable kubectl autocompletion
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  become: yes

- name: show message source bashrc
  ansible.builtin.debug:
    msg:
      - if kubectl autocomplete does not work in terminal session use `source ~/.bashrc` to enable it
